version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: food_delivery
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql 

  user-service:
    build:
      context: .
      dockerfile: user-service/Dockerfile
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      PORT: 3001
    depends_on:
      - postgres

  restaurant-service:
    build:
      context: .
      dockerfile: restaurant-service/Dockerfile
    ports:
      - "3002:3002"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      PORT: 3002
    depends_on:
      - postgres

  delivery-service:
    build:
      context: .
      dockerfile: delivery-service/Dockerfile
    ports:
      - "3003:3003"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      PORT: 3003
    depends_on:
      - postgres

volumes:
  postgres_data:
