services:
  # User Service
  - type: web
    name: user-service
    env: docker
    plan: starter
    dockerfilePath: ./user-service/Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: USER_SERVICE_PORT
        value: 3001
      - key: RESTAURANT_SERVICE_PORT
        value: 3002
      - key: DELIVERY_SERVICE_PORT
        value: 3003
      - key: USER_SERVICE_URL
        fromService:
          type: web
          name: user-service
          property: host
      - key: RESTAURANT_SERVICE_URL
        fromService:
          type: web
          name: restaurant-service
          property: host
      - key: DELIVERY_SERVICE_URL
        fromService:
          type: web
          name: delivery-service
          property: host
      - key: DATABASE_URL
        fromDatabase:
          name: food-delivery-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: RATE_LIMIT_WINDOW_MS
        value: 900000
      - key: RATE_LIMIT_MAX_REQUESTS
        value: 100
      - key: DB_POOL_MIN
        value: 2
      - key: DB_POOL_MAX
        value: 10
      - key: LOG_LEVEL
        value: info
      - key: RUN_MIGRATIONS
        value: true

  # Restaurant Service
  - type: web
    name: restaurant-service
    env: docker
    plan: starter
    dockerfilePath: ./restaurant-service/Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3002
      - key: USER_SERVICE_PORT
        value: 3001
      - key: RESTAURANT_SERVICE_PORT
        value: 3002
      - key: DELIVERY_SERVICE_PORT
        value: 3003
      - key: USER_SERVICE_URL
        fromService:
          type: web
          name: user-service
          property: host
      - key: RESTAURANT_SERVICE_URL
        fromService:
          type: web
          name: restaurant-service
          property: host
      - key: DELIVERY_SERVICE_URL
        fromService:
          type: web
          name: delivery-service
          property: host
      - key: DATABASE_URL
        fromDatabase:
          name: food-delivery-db
          property: connectionString
      - key: JWT_SECRET
        sync: false
      - key: RATE_LIMIT_WINDOW_MS
        value: 900000
      - key: RATE_LIMIT_MAX_REQUESTS
        value: 100
      - key: DB_POOL_MIN
        value: 2
      - key: DB_POOL_MAX
        value: 10
      - key: LOG_LEVEL
        value: info

  # Delivery Service
  - type: web
    name: delivery-service
    env: docker
    plan: starter
    dockerfilePath: ./delivery-service/Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3003
      - key: USER_SERVICE_PORT
        value: 3001
      - key: RESTAURANT_SERVICE_PORT
        value: 3002
      - key: DELIVERY_SERVICE_PORT
        value: 3003
      - key: USER_SERVICE_URL
        fromService:
          type: web
          name: user-service
          property: host
      - key: RESTAURANT_SERVICE_URL
        fromService:
          type: web
          name: restaurant-service
          property: host
      - key: DELIVERY_SERVICE_URL
        fromService:
          type: web
          name: delivery-service
          property: host
      - key: DATABASE_URL
        fromDatabase:
          name: food-delivery-db
          property: connectionString
      - key: JWT_SECRET
        sync: false
      - key: RATE_LIMIT_WINDOW_MS
        value: 900000
      - key: RATE_LIMIT_MAX_REQUESTS
        value: 100
      - key: DB_POOL_MIN
        value: 2
      - key: DB_POOL_MAX
        value: 10
      - key: LOG_LEVEL
        value: info

databases:
  - name: food-delivery-db
    databaseName: food_delivery
    plan: starter