apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: food-delivery
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: your-registry/user-service:latest
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: url
        - name: PORT
          value: "3001"
        ports:
        - containerPort: 3001

---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: food-delivery
spec:
  selector:
    app: user-service
  ports:
  - port: 80
    targetPort: 3001
  type: LoadBalancer